/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PoliciesShippingPolicyRouteImport } from './routes/policies.shipping-policy'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCollectionIdIndexRouteImport } from './routes/shop.$collectionId.index'
import { Route as ShopCollectionIdProductIdRouteImport } from './routes/shop.$collectionId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingPolicyRoute = PoliciesShippingPolicyRouteImport.update({
  id: '/policies/shipping-policy',
  path: '/policies/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionIdIndexRoute = ShopCollectionIdIndexRouteImport.update({
  id: '/$collectionId/',
  path: '/$collectionId/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionIdProductIdRoute =
  ShopCollectionIdProductIdRouteImport.update({
    id: '/$collectionId/$productId',
    path: '/$collectionId/$productId',
    getParentRoute: () => ShopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/policies/shipping-policy': typeof PoliciesShippingPolicyRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/$collectionId/$productId': typeof ShopCollectionIdProductIdRoute
  '/shop/$collectionId/': typeof ShopCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/policies/shipping-policy': typeof PoliciesShippingPolicyRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/$collectionId/$productId': typeof ShopCollectionIdProductIdRoute
  '/shop/$collectionId': typeof ShopCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/policies/shipping-policy': typeof PoliciesShippingPolicyRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/$collectionId/$productId': typeof ShopCollectionIdProductIdRoute
  '/shop/$collectionId/': typeof ShopCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin/login'
    | '/policies/shipping-policy'
    | '/admin/'
    | '/shop/'
    | '/shop/$collectionId/$productId'
    | '/shop/$collectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/admin/login'
    | '/policies/shipping-policy'
    | '/admin'
    | '/shop'
    | '/shop/$collectionId/$productId'
    | '/shop/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin/login'
    | '/policies/shipping-policy'
    | '/admin/'
    | '/shop/'
    | '/shop/$collectionId/$productId'
    | '/shop/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PoliciesShippingPolicyRoute: typeof PoliciesShippingPolicyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping-policy': {
      id: '/policies/shipping-policy'
      path: '/policies/shipping-policy'
      fullPath: '/policies/shipping-policy'
      preLoaderRoute: typeof PoliciesShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$collectionId/': {
      id: '/shop/$collectionId/'
      path: '/$collectionId'
      fullPath: '/shop/$collectionId/'
      preLoaderRoute: typeof ShopCollectionIdIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$collectionId/$productId': {
      id: '/shop/$collectionId/$productId'
      path: '/$collectionId/$productId'
      fullPath: '/shop/$collectionId/$productId'
      preLoaderRoute: typeof ShopCollectionIdProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionIdProductIdRoute: typeof ShopCollectionIdProductIdRoute
  ShopCollectionIdIndexRoute: typeof ShopCollectionIdIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionIdProductIdRoute: ShopCollectionIdProductIdRoute,
  ShopCollectionIdIndexRoute: ShopCollectionIdIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PoliciesShippingPolicyRoute: PoliciesShippingPolicyRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
